# Generated by Django 4.1.2 on 2022-10-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudeapp', '0005_alter_post_food_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='food_img',
            field=models.CharField(max_length=500),
        ),
    ]
