# Generated by Django 4.1.2 on 2022-10-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudeapp', '0008_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(max_length=120),
        ),
    ]
